language: node_js
node_js:
- '0.10'
branches:
  only:
  - source
before_install:
- npm install -g grunt-cli
- npm install -g wintersmith
install:
- npm install
script:
- grunt deploy
env:
  global:
    secure: US3UsZbZkt6G/k+MsgUJNel3/2cW1EcJEKH4DnGqlb4+c0Wcqh3W9ZO/nlTOT7+sa8SrMaR0qVGDr8MQqt/zxWMTMe1xh3zgOiOl7Sdq4sGefvVwg2FPanrZ/ErfUaXUYZ4eFGPM4qfciR264XLo+4/pendX6hoKpR56ryAdHys=
